# Generated by Django 4.1.5 on 2023-01-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='tecnologia',
            field=models.CharField(max_length=100, verbose_name='tecnologia'),
        ),
    ]
